plugins { id 'com.android.application' }
android {
    namespace 'com.blur.cache'
    compileSdk 33
    defaultConfig {
        applicationId "com.blur.cache"
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes { release { minifyEnabled false; shrinkResources false } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
